const fighters = [
  "Yoshi",
  "Samus",
  "Pikachu",
  "Ness",
  "Mario",
  "Luigi",
  "Link",
  "Kirby",
  "Jigglypuff",
  "Fox",
  "Donkey Kong",
  "Captain Falcon",
  "Bowser",
  "King Dedede",
  "Mewtwo",
  "Marth",
  "Banjo & Kazooie",
  "Bayonetta",
  "Bowser Jr.",
  "Byleth",
  "Charizard",
  "Chrom",
  "Cloud",
  "Corrin",
  "Daisy",
  "Dark Pit",
  "Dark Samus",
  "Diddy Kong",
  "Dr. Mario",
  "Duck Hunt",
  "Falco",
  "Ganondorf",
  "Greninja",
  "Hero",
  "Ice Climbers",
  "Ike",
  "Incineroar",
  "Inkling",
  "Isabelle",
  "Ivysaur",
  "Joker",
  "Ken",
  "King K. Rool",
  "Little Mac",
  "Lucario",
  "Lucas",
  "Lucina",
  "Mega Man",
  "Meta Knight",
  "Mii Brawler",
  "Mii Gunner",
  "Mii Swordfighter",
  "Mr. Game & Watch",
  "Olimar",
  "Pac-Man",
  "Palutena",
  "Peach",
  "Pichu",
  "Piranha Plant",
  "Pit",
  "Pokémon Trainer",
  "R.O.B.",
  "Richter",
  "Ridley",
  "Robin",
  "Rosalina & Luma",
  "Roy",
  "Ryu",
  "Sheik",
  "Shulk",
  "Simon",
  "Snake",
  "Sonic",
  "Squirtle",
  "Terry",
  "Toon Link",
  "Villager",
  "Wario",
  "Wii Fit Trainer",
  "Wolf",
  "Young Link",
  "Zelda",
  "Zero Suit Samus"
];

const stages = [
  "Battlefield",
  "Big Battlefield",
  "Final Destination",
  "3D Land",
  "75m",
  "Arena Ferox",
  "Balloon Fight",
  "Big Blue",
  "Boxing Ring",
  "Bridge of Eldin",
  "Brinstar",
  "Brinstar Depths",
  "Castle Siege",
  "Coliseum",
  "Corneria",
  "Delfino Plaza",
  "Distant Planet",
  "Dracula's Castle",
  "Dream Land ",
  "Dream Land GB",
  "Duck Hunt",
  "Figure-8 Circuit",
  "Find Mii",
  "Flat Zone X",
  "Fountain of Dreams",
  "Fourside",
  "Frigate Orpheon",
  "Gamer",
  "Garden of Hope",
  "Garreg Mach Monastery",
  "Gaur Plain",
  "Gerudo Valley",
  "Golden Plains",
  "Great Bay",
  "The Great Cave Offensive",
  "Great Plateau Tower",
  "Green Greens",
  "Green Hill Zone",
  "Halberd",
  "Hanenbow",
  "Hyrule Castle",
  "Jungle Japes",
  "Kalos Pokémon League",
  "King of Fighters Stadium",
  "Kongo Falls",
  "Kongo Jungle ",
  "Living Room",
  "Luigi's Mansion",
  "Lylat Cruise",
  "Magicant",
  "Mario Bros.",
  "Mario Circuit ",
  "Mario Galaxy",
  "Mementos",
  "Midgar",
  "Moray Towers",
  "Mushroom Kingdom ",
  "Mushroom Kingdom II",
  "Mushroom Kingdom U",
  "Mute City SNES",
  "New Donk City Hall",
  "New Pork City",
  "Norfair",
  "Onett",
  "Pac-Land",
  "Palutena's Temple",
  "Paper Mario",
  "Peach's Castle",
  "Princess Peach's Castle",
  "PictoChat 2",
  "Pilotwings",
  "Pirate Ship",
  "Pokémon Stadium",
  "Pokémon Stadium 2",
  "Port Town Aero Dive",
  "Prism Tower",
  "Rainbow Cruise",
  "Reset Bomb Forest",
  "Saffron City",
  "Shadow Moses Island",
  "Skyloft",
  "Skyworld",
  "Smashville",
  "Spear Pillar",
  "Spiral Mountain",
  "Spirit Train",
  "Summit",
  "Super Happy Tree",
  "Super Mario Maker",
  "Suzaku Castle",
  "Temple",
  "Tomodachi Life",
  "Tortimer Island",
  "Town and City",
  "Umbra Clock Tower",
  "Unova Pokémon League",
  "Venom",
  "WarioWare, Inc.",
  "Wii Fit Studio",
  "Windy Hill Zone",
  "Wrecking Crew",
  "Wuhu Island",
  "Yggdrasil's Altar",
  "Yoshi's Island ",
  "Yoshi's Island ",
  "Yoshi's Story",
  "Mushroomy Kingdom",
  "Wily Castle"
]